project:
  type: website
  output-dir: docs
excute:
  freeze: auto
website:
  title: "Daiil Jun"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - publication.qmd
      - blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


